version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/djangobnb_backend/media
  web:
    build: ./djangobnb_backend
    command: gunicorn djangobnb_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/usr/src/djangobnb_backend/media
    expose:
      - 8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - DATABASE=${DATABASE}
    depends_on:
      - db
  daphne:
    build: ./djangobnb_backend
    entrypoint: []
    command: sh -c "sleep 15 && daphne --bind 0.0.0.0 -p 8002 djangobnb_backend.asgi:application"
    ports:
      - 8002:8002
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - DATABASE=${DATABASE}
    depends_on:
      - web
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:
  media_volume:
